title: Dragon's notes
tagline: Posts about IT, photography and bicycles.
description: Dragon's cave with posts about IT, photography, bicycles and different DIY.
email: evg.andrienko@gmail.com
author: Eugene Andrienko
social:
  name: Eugene Andrienko
  links:
    - https://mas.to/@evgandr
logo: "/assets/images/home.webp"
url: "https://eugene-andrienko.com"
theme_color: "#696969"
brand_color: "#696969"
defaults:
  home:
    heading: "Dragon's notes"
    subheading: "Force sand to think"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
port: 8000
languages: ["en", "ru"]
lang: "ru"
default_lang: "ru"
exclude_from_localization: ["assets"]
parallel_localization: true
lang_from_path: true
future: true
header_pages:
  - now.html
  - about.html
  - uses.html
  - links.html
  - cv.html
  - tags.html
  - categories.html
  - archives.html
  - changelog.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-polyglot
  - jekyll-minifier

jekyll-minifier:
  exclude: ["feed.xml", "sitemap.xml"]
  preserve_php: false
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_json: false
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: true
  simple_boolean_attributes: false
