title: Dragon's notes
tagline: Posts about IT, photography and bicycles.
description: Dragon's cave with posts about IT, photography, bicycles and different DIY.
email: evg.andrienko@gmail.com
author: Eugene Andrienko
social:
  name: Eugene Andrienko
  links:
    - https://mas.to/@evgandr
logo: "/assets/images/home.jpg"
url: "https://eugene-andrienko.com"
yat:
  date_format: "%d %b %Y"
theme_color: "#696969"
brand_color: "#696969"
defaults:
  home:
    heading: "Dragon's notes"
    subheading: "Force sand to think"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
port: 8000
languages: ["en", "ru"]
lang: "ru"
default_lang: "ru"
exclude_from_localization: ["assets"]
parallel_localization: true
lang_from_path: true
future: true
sass:
  sourcemap: never
header_pages:
  - now.html
  - about.html
  - uses.html
  - links.html
  - cv.html
  - tags.html
  - categories.html
  - archives.html
  - changelog.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-polyglot
