title: Dragon's notes
email: evg.andrienko@gmail.com
author: Eugene Andrienko
copyright: "Dragon's blog (cleft): 2020-{currentYear} {author}"
url: "https://eugene-andrienko.com"
yat:
  date_format: "%d %b %Y"
theme_color: "#696969"
brand_color: "#696969"
defaults:
  home:
    heading: "Dragon's notes"
    subheading: "Заставляю песок думать"
markdown: kramdown
kmarkdown:
  input: GFM
port: 8000
lang: "ru"
translate_langs: []
header_pages:
  - about.html
  - cv.html
  - tags.html
  - archives.html
disqus:
  shortname: "eugene-andrienko-com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-pdf-embed
