title: Dragon's notes
email: evg.andrienko@gmail.com
author: Eugene Andrienko
copyright: "Dragon's blog (cleft): 2020-{currentYear} {author}"
url: "https://eugene-andrienko.com"
yat:
  date_format: "%d %b %Y"
theme_color: "#696969"
brand_color: "#696969"
defaults:
  home:
    heading: "Dragon's notes"
    subheading: "Force sand to think"
markdown: kramdown
kmarkdown:
  input: GFM
port: 8000
languages: ["en", "ru"]
lang: "ru"
default_lang: "ru"
exclude_from_localization: ["assets"]
parallel_localization: true
lang_from_path: true
sass:
  sourcemap: never
header_pages:
  - about.html
  - cv.html
  - tags.html
  - categories.html
  - archives.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-polyglot
